export const mockHotels = [
  {
    id: 1,
    name: "Le Meurice",
    address: "228 Rue de Rivoli",
    city: "Paris",
    state: "IDF",
    country_code: "FR",
    hotel_rating: 5,
    phone_number: "+33144581010",
    website: null,
  },
  {
    id: 2,
    name: "The Ritz Paris",
    address: "15 Place Vendôme",
    city: "Paris",
    state: "IDF",
    country_code: "FR",
    hotel_rating: 5,
    phone_number: "+33143163030",
    website: null,
  },
  {
    id: 3,
    name: "Shangri-La Paris",
    address: "10 Av. d'Iéna",
    city: "Paris",
    state: "IDF",
    country_code: "FR",
    hotel_rating: 5,
    phone_number: "+33153671998",
    website: null,
  },
  {
    id: 4,
    name: "Savoy Hotel",
    address: "Strand, London WC2R 0EZ",
    city: "London",
    state: "ENG",
    country_code: "GB",
    hotel_rating: 5,
    phone_number: "+442078364343",
    website: null,
  },
  {
    id: 5,
    name: "The Dorchester",
    address: "53 Park Ln, London",
    city: "London",
    state: "ENG",
    country_code: "GB",
    hotel_rating: 5,
    phone_number: "+442076298888",
    website: null,
  },
  {
    id: 6,
    name: "The Langham",
    address: "1C Portland Pl",
    city: "London",
    state: "ENG",
    country_code: "GB",
    hotel_rating: 5,
    phone_number: "+442076361000",
    website: null,
  },
  {
    id: 7,
    name: "The Plaza",
    address: "768 5th Ave",
    city: "New York",
    state: "NY",
    country_code: "US",
    hotel_rating: 5,
    phone_number: "+12127593000",
    website: null,
  },
  {
    id: 8,
    name: "The Pierre",
    address: "2 E 61st St",
    city: "New York",
    state: "NY",
    country_code: "US",
    hotel_rating: 5,
    phone_number: "+12128388000",
    website: null,
  },
  {
    id: 9,
    name: "St. Regis New York",
    address: "Two E 55th St",
    city: "New York",
    state: "NY",
    country_code: "US",
    hotel_rating: 5,
    phone_number: "+12127534500",
    website: null,
  },
  {
    id: 10,
    name: "Park Hyatt Tokyo",
    address: "3-7-1-2 Nishi-Shinjuku",
    city: "Tokyo",
    state: "TK",
    country_code: "JP",
    hotel_rating: 5,
    phone_number: "+81353221234",
    website: null,
  },
  {
    id: 11,
    name: "Aman Tokyo",
    address: "1-5-6 Otemachi",
    city: "Tokyo",
    state: "TK",
    country_code: "JP",
    hotel_rating: 5,
    phone_number: "+81352243333",
    website: null,
  },
  {
    id: 12,
    name: "Imperial Hotel",
    address: "1-1-1 Uchisaiwaicho",
    city: "Tokyo",
    state: "TK",
    country_code: "JP",
    hotel_rating: 5,
    phone_number: "+81335041111",
    website: null,
  },
  {
    id: 13,
    name: "Hotel Hassler",
    address: "Piazza della Trinità dei Monti, 6",
    city: "Rome",
    state: "RM",
    country_code: "IT",
    hotel_rating: 5,
    phone_number: "+3906699341",
    website: null,
  },
  {
    id: 14,
    name: "Hotel de Russie",
    address: "Via del Babuino, 9",
    city: "Rome",
    state: "RM",
    country_code: "IT",
    hotel_rating: 5,
    phone_number: "+3906328881",
    website: null,
  },
  {
    id: 15,
    name: "Hotel de la Ville",
    address: "Via Sistina, 69",
    city: "Rome",
    state: "RM",
    country_code: "IT",
    hotel_rating: 5,
    phone_number: "+3906977931",
    website: null,
  },
  {
    id: 16,
    name: "W Barcelona",
    address: "Plaça de la Rosa dels Vents, 1",
    city: "Barcelona",
    state: "CT",
    country_code: "ES",
    hotel_rating: 5,
    phone_number: "+34932952800",
    website: null,
  },
  {
    id: 17,
    name: "Majestic Hotel",
    address: "Passeig de Gràcia, 68",
    city: "Barcelona",
    state: "CT",
    country_code: "ES",
    hotel_rating: 5,
    phone_number: "+34934881717",
    website: null,
  },
  {
    id: 18,
    name: "Mandarin Oriental",
    address: "Passeig de Gràcia, 38",
    city: "Barcelona",
    state: "CT",
    country_code: "ES",
    hotel_rating: 5,
    phone_number: "+34931518888",
    website: null,
  },
  {
    id: 19,
    name: "Burj Al Arab",
    address: "Jumeirah St",
    city: "Dubai",
    state: "DU",
    country_code: "AE",
    hotel_rating: 5,
    phone_number: "+97143017777",
    website: null,
  },
  {
    id: 20,
    name: "Atlantis The Palm",
    address: "Crescent Rd",
    city: "Dubai",
    state: "DU",
    country_code: "AE",
    hotel_rating: 5,
    phone_number: "+97144262000",
    website: null,
  },
  {
    id: 21,
    name: "Armani Hotel",
    address: "Burj Khalifa",
    city: "Dubai",
    state: "DU",
    country_code: "AE",
    hotel_rating: 5,
    phone_number: "+97148883888",
    website: null,
  },
  {
    id: 22,
    name: "Grand Hotel Bohemia",
    address: "Králodvorská 652/4",
    city: "Prague",
    state: "PR",
    country_code: "CZ",
    hotel_rating: 5,
    phone_number: "+420234608111",
    website: null,
  },
  {
    id: 23,
    name: "Augustine Hotel",
    address: "Letenská 12/33",
    city: "Prague",
    state: "PR",
    country_code: "CZ",
    hotel_rating: 5,
    phone_number: "+420266112233",
    website: null,
  },
  {
    id: 24,
    name: "Four Seasons Prague",
    address: "Veleslavínova 1098/2",
    city: "Prague",
    state: "PR",
    country_code: "CZ",
    hotel_rating: 5,
    phone_number: "+420221427000",
    website: null,
  },
  {
    id: 25,
    name: "Pulitzer Amsterdam",
    address: "Prinsengracht 323",
    city: "Amsterdam",
    state: "NH",
    country_code: "NL",
    hotel_rating: 5,
    phone_number: "+31205235235",
    website: null,
  },
  {
    id: 26,
    name: "Conservatorium Hotel",
    address: "Paulus Potterstraat 50",
    city: "Amsterdam",
    state: "NH",
    country_code: "NL",
    hotel_rating: 5,
    phone_number: "+31205700000",
    website: null,
  },
  {
    id: 27,
    name: "De L’Europe",
    address: "Nieuwe Doelenstraat 2",
    city: "Amsterdam",
    state: "NH",
    country_code: "NL",
    hotel_rating: 5,
    phone_number: "+31205311777",
    website: null,
  },
  {
    id: 28,
    name: "Hotel Adlon Kempinski",
    address: "Unter den Linden 77",
    city: "Berlin",
    state: "BE",
    country_code: "DE",
    hotel_rating: 5,
    phone_number: "+493022610",
    website: null,
  },
  {
    id: 29,
    name: "The Westin Grand",
    address: "Friedrichstraße 158",
    city: "Berlin",
    state: "BE",
    country_code: "DE",
    hotel_rating: 5,
    phone_number: "+493020270",
    website: null,
  },
  {
    id: 30,
    name: "Waldorf Astoria Berlin",
    address: "Hardenbergstraße 28",
    city: "Berlin",
    state: "BE",
    country_code: "DE",
    hotel_rating: 5,
    phone_number: "+4930814000",
    website: null,
  },
];

export const mockDestinations = [
  { id: "all", label: "All available hotels" },
  { id: "1", label: "Paris" },
  { id: "2", label: "London" },
  { id: "3", label: "New York" },
  { id: "4", label: "Tokyo" },
  { id: "5", label: "Rome" },
  { id: "6", label: "Barcelona" },
  { id: "7", label: "Dubai" },
  { id: "8", label: "Prague" },
  { id: "9", label: "Amsterdam" },
  { id: "10", label: "Berlin" },
];
